[package]
name = "korchevatel"
version = "0.1.0"
edition = "2024"

[dependencies]
avian2d = { version = "0.5.0", features = ["debug-plugin", "bevy_diagnostic", "diagnostic_ui"] }
bevy = { version = "0.18.0", features = ["debug"] }
bevy_ecs_tiled = { version = "0.11.2", features = ["avian", "physics", "user_properties"] }
bevy-inspector-egui = "0.36.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
anyhow = "1.0.100"
humantime-serde = "1.1.1"
rand = "0.9.2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"
